# Generated by Django 3.2.20 on 2023-07-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20230710_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organisation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
