# Generated by Django 3.2.20 on 2023-07-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20230721_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-07-20'),
            preserve_default=False,
        ),
    ]
