# Generated by Django 3.2.20 on 2023-07-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_start_date'),
        ('profiles', '0003_auto_20230710_1829'),
        ('members', '0003_member_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('profile', 'project')},
        ),
    ]
