# Generated by Django 3.2.20 on 2023-07-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20230710_1829'),
        ('projects', '0003_alter_project_start_date'),
        ('members', '0005_alter_member_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('profile', 'project')},
        ),
    ]
